### ISSUE TITLE
I can't implement it

### ISSUE THREAD

**Issue by Pouidesbois** [punkhomov/ktor-client-rate-limit#1]
I spend the last hour trying to find a solution but I just can't, 
The only way i managed to implement it was with this line :
 implementation("com.github.punkhomov.ktor-client-rate-limit:ktor-client-rate-limit:v0.0.1-alpha-1")
All the others lines i found on JitPack didn't work, it just said "couldn't find source something" as the error
and with the line gradles didn't crash on, i have this error when i try to run my program I have this error :
Module was compiled with an incompatible version of Kotlin, The binary version of its metadata is 1.7.1, expected version is 1.5.1.

Thanks in advance

**Comment by binarynoise** [comment]
@Pouidesbois 
Which kotlin version do you use? If you are still on 1.5.1 you need to update to at least 1.7.1

**Comment by Pouidesbois** [comment]
I had some big issue on my gradle and my package / project structure, I redid it all and i was able to upgrade kotlin with a lot of others modules that were outdated, sorry I forgot to close the issue when it worked !
Thanks a lot for this module, it works as intended !
